project_name: team-divider

release:
  prerelease: auto
  draft: true
  name_template: "Team divider {{.Version}}"

before:
  hooks:
    - go mod tidy

builds:
  - <<: &build_defaults
      binary: bin/team-divider
      main: ./cmd/app
      ldflags:
        - -X github.com/Aldebaranoro/team-divider/internal/config.buildVersion={{.Version}}
        - -X github.com/Aldebaranoro/team-divider/internal/config.buildCommit={{.Commit}}
        - -X github.com/Aldebaranoro/team-divider/internal/config.buildDate={{.Date}}

  - <<: *build_defaults
    id: macos
    goos: [ darwin ]
    goarch: [ amd64 ]

  - <<: *build_defaults
    id: linux
    goos: [ linux ]
    goarch: [ 386, arm, amd64, arm64 ]
    env:
      - CGO_ENABLED=0

  - <<: *build_defaults
    id: windows
    goos: [ windows ]
    goarch: [ 386, amd64, arm64 ]

archives:
  - id: nix
    builds: [ macos, linux ]
    <<: &archive_defaults
      name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    wrap_in_directory: true
    replacements:
      darwin: macOS
    format: tar.gz
    files:
      - LICENSE
  - id: windows
    builds: [ windows ]
    <<: *archive_defaults
    wrap_in_directory: false
    format: zip
    files:
      - LICENSE


brews:
  - name: team-divider
    homepage: https://github.com/Aldebaranoro/team-divider
    tap:
      owner: Aldebaranoro
      name: team-divider
