# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TeamDivider < Formula
  desc ""
  homepage "https://github.com/Aldebaranoro/team-divider"
  version "1.1.1"

  on_macos do
    url "https://github.com/Aldebaranoro/team-divider/releases/download/v1.1.1/team-divider_1.1.1_macOS_amd64.tar.gz"
    sha256 "3e033c73532fccb015dd477c37f1cb790c81272b6d2e203776be80ec57912e19"

    def install
      bin.install "bin/team-divider"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the TeamDivider
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Aldebaranoro/team-divider/releases/download/v1.1.1/team-divider_1.1.1_linux_amd64.tar.gz"
      sha256 "f2923de776488076f46e02cb65caf45ce54415bd615d059dc35e7965b3c9780a"

      def install
        bin.install "bin/team-divider"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Aldebaranoro/team-divider/releases/download/v1.1.1/team-divider_1.1.1_linux_arm64.tar.gz"
      sha256 "8af0ea19357baf46e975769b8201653d69425e4dd27a791359cef62b028b3035"

      def install
        bin.install "bin/team-divider"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/Aldebaranoro/team-divider/releases/download/v1.1.1/team-divider_1.1.1_linux_armv6.tar.gz"
      sha256 "5b46a455d4bed89f1445886cd992755f35cd93adabb15c5b7dd56af4d8bfb240"

      def install
        bin.install "bin/team-divider"
      end
    end
  end
end
