# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TeamDivider < Formula
  desc ""
  homepage "https://github.com/Aldebaranoro/team-divider"
  version "1.1.2"

  on_macos do
    url "https://github.com/Aldebaranoro/team-divider/releases/download/v1.1.2/team-divider_1.1.2_macOS_amd64.tar.gz"
    sha256 "8f64c8911150f7e535ce4b42546bb79efa2dcfc8daf2c4a3d00633cbbedd5f82"

    def install
      bin.install "bin/team-divider"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the TeamDivider
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Aldebaranoro/team-divider/releases/download/v1.1.2/team-divider_1.1.2_linux_amd64.tar.gz"
      sha256 "fe55eaaf439f426902de639edbbec90f2d498b45893758740742d3b64fd97d93"

      def install
        bin.install "bin/team-divider"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Aldebaranoro/team-divider/releases/download/v1.1.2/team-divider_1.1.2_linux_arm64.tar.gz"
      sha256 "7f79d70b53eb1aa7ef870bbdfc9894e1c2e040d8e63d337c46588fffbaedde33"

      def install
        bin.install "bin/team-divider"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/Aldebaranoro/team-divider/releases/download/v1.1.2/team-divider_1.1.2_linux_armv6.tar.gz"
      sha256 "320932f366bd31051875fe0aa674b3c05dc68cdb8bd64db4d2aa45dad5cf658e"

      def install
        bin.install "bin/team-divider"
      end
    end
  end
end
